services:
  - type: web
    name: wartungsapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DEBUG
        value: false
      - key: FLASK_ENV
        value: production